# Generated by Django 2.0 on 2018-01-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=200)),
                ('ItemPrice', models.CharField(max_length=200)),
                ('ItemLogo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemCategory', models.CharField(max_length=200)),
                ('ItemRate', models.CharField(max_length=400)),
                ('ItemReview', models.CharField(max_length=1000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
            ],
        ),
    ]
