# Generated by Django 2.0 on 2018-01-31 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemdetail',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='ItemRate',
            field=models.FloatField(default=0.0, max_length=400),
        ),
        migrations.DeleteModel(
            name='ItemDetail',
        ),
        migrations.AddField(
            model_name='item',
            name='ItemCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
    ]
