# Generated by Django 2.0 on 2018-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180131_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ItemDetails',
            field=models.CharField(default='Nothing', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemLogo',
            field=models.ImageField(blank=True, null=True, upload_to='products/static/products/images'),
        ),
    ]
