# Generated by Django 2.0 on 2018-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180201_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.IntegerField(default=0),
        ),
    ]
