# Generated by Django 2.0 on 2018-02-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180201_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='itemId',
        ),
    ]
