# Generated by Django 2.0 on 2018-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180201_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='stars',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
