# Generated by Django 2.0 on 2018-02-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_comment_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='graystars',
            field=models.CharField(default='xxxxx', max_length=5, null=True),
        ),
    ]
