# Generated by Django 2.0 on 2018-02-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_comment_graystars'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='graystars',
            field=models.CharField(default='xxxxx', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stars',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
