# Generated by Django 2.0 on 2018-02-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180201_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stars',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
