# Generated by Django 2.0 on 2018-02-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180201_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemPrice',
            field=models.FloatField(default=0.0, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='stars',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
