# Generated by Django 2.0 on 2018-02-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180202_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ItemPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemRate',
            field=models.FloatField(default=0.0),
        ),
    ]
