# Generated by Django 2.0 on 2018-02-04 20:43

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20180204_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cart',
            field=models.BooleanField(verbose_name=products.models.Cart),
        ),
    ]
