# Generated by Django 2.0 on 2018-02-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20180204_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ItemsNumber',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='TotalPay',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
