# Generated by Django 2.0 on 2018-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20180205_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='TotalPay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='UserId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
